const SUPER_ADMIN_ROLE = 1
const PHARMACY_ADMIN_ROLE = 2
const DOCTOR_ROLE = 3
const PATIENT_ROLE = 4

const PAYMENT_STATUS = {
  UNPAID: 1,
  WAITING_FOR_CONFIRMATION: 2,
  PAYMENT_RECEIVED: 3,
  PAID: 4,
}
